### ISSUE TITLE
H.U 4 Funcionalidad espacio de juego 

### ISSUE THREAD

**Issue by Soflorez1** [andresfgal/co.edu.poli.wordle#11]
Como usuario
Quiero presionar las teclas del teclado
Para que visualicen en la matriz del juego

C.A

- [x] Luego de codificar la visualización de la matriz de juego se debe poder escribir en cada espacio de la matriz
- [x] Solo se deberá poder escribir una sola letra en cada espacio de la matriz

Tasks 

- [x] Crear archivo en Java Swing con el patrón MVC (Modelo, Vista, Controlador)
- [x] Crear en la vista los campos de texto según la matriz 6*5 para ingresar las letras de la palabra

RNF
- [x] Debe estar desarrollado en Java Swing
- [x] Las letras mostradas en la matriz deben ser de color negro
- [x] Las letras deben ir centradas en cada espacio de la matriz de juego.
- [x] Las letras deberán aparecer en la matriz de izquierda a derecha con el orden de cada intento, primero se completará la primera fila (1), luego de estar completa seguirá el orden con la fila (2) y así sucesivamente.

**Comment by wipacheco1** [comment]
Como usuario
Quiero presionar las teclas del teclado
Para que visualicen en la matriz del juego
