### ISSUE TITLE
H.U 6 Base de datos

### ISSUE THREAD

**Issue by Soflorez1** [andresfgal/co.edu.poli.wordle#12]
Como programador
Quiero crear una base de datos con una tabla
Para poder crear un listado de palabras

C.A

- [x] Crear un listado de palabras
 
Tasks

- [x] Desde SQL server generar la creación de la base de datos
- [x] Crear una tabla en la cual se guarden el listado de palabras a validar

RNF

- [x] El tiempo de respuesta a una consulta debe ser inmediato
- [x] La BD se creara en SQL server

**Comment by wipacheco1** [comment]
Como programador
Quiero crear una base de datos con una lista de palabras
Para verificar si es correcta
