### ISSUE TITLE
H.U 7 Mensajes de error

### ISSUE THREAD

**Issue by Soflorez1** [andresfgal/co.edu.poli.wordle#14]
Como usuario 
Quiero mostrar mensajes de error
Para advertir que la palabra  no se encuentren en la lista.

C.A

- [x]  Mostrar un mensaje de error cada vez que la palabra no se encuentre en la lista de la base de datos. 
- [x]  Los mensajes de error deber ser color rojo con signo de interrogación.

<img width="173" alt="image" src="https://user-images.githubusercontent.com/79174696/189706811-3013eb0d-258a-41f2-9556-9e7ff83d9138.png">

Task

- [x]  Validar la palabra escrita por el jugador (5 letras en un intento) con la lista de la base de datos.
- [x] Si la palabra no se encuentra en la base de datos se generará el mensaje de error.
- [x]  El mensaje de error debera aparecer luego de dar clic en el comando enter solo si la palabra no se encuentra en la lista.
- [x] El mensaje de error deberá estar progrogramado para aparecer en la parte superior de la pantalla. 

<img width="255" alt="image" src="https://user-images.githubusercontent.com/79174696/189715109-2c62dc0a-7e4a-4e09-ab49-21fcac66a3d2.png">

RNF:

- [ ]  El mensaje de error deberá tener la letra tamaño 16 
- [x]  El mensaje deberá tener la letra color rojo.
- [x]  El mensaje deberá tener la letra tipo Arial.
- [x]  El mensaje deberá estar ubicado dentro de un cuadro.
- [x]  El mensaje deberá estar centrado en la parte superior de la ventana de espacio de juego.

**Comment by wipacheco1** [comment]
Como usuario
Quiero verificar si la palabra esta mal escrita
Para enviar un mensaje de error al jugador y la vuelva a digitar
