### ISSUE TITLE
H.U 8 Conexión a la  base de datos

### ISSUE THREAD

**Issue by Soflorez1** [andresfgal/co.edu.poli.wordle#15]
Como programador
Quiero realizar la conexión entre la base de datos y el dao del programa wordle
Para realizar la consulta de la palabra ingresada en la matriz de juego

C.A

- [x] La base de datos debe responder a las consultas de las palabras necesarias para el programa wordle (SELECT * FROM...)

- [x] La base de datos debe devolver un valor booleano como respuesta a la consulta teniendo en cuenta si la palabra se encuentra o no en la base
- [x] El modelo se debera implementar el co.wordle.dao

TASK

- [x] Crear modulo vista
- [x] Crear modulo controlador
- [x] Crear modulo modelo
- [x] Crear en java el modulo com.wordle.dao 
- [x] implementar la conexión a la base de datos creada en el sprint 2 y 3

RNF

- [x] La lógica de la matriz del juego debe tener restricción para el uso de números y caracteres especiales.

**Comment by wipacheco1** [comment]
Como usuario
Quiero que al digitar una palabra se valide contra la base de datos
Para saber si es correcta o incorrecta

**Comment by andresfgal** [comment]
Como programador
Quiero realizar la conexion entre la base de datos y el dao del programa wordle
Para realizar la consulta de la palabra ingresada en la matriz de juego


C.A

La base de datos debe responder a las consultas de las palabras necesarias para el programa wordle (SELECT * FROM...) 
La base de datos dere devolver un valor booleano como respuesta a la consulta teniendo en cuenta si la palabra se encuentra o no en la base



TASK


Crear modulo vista
Crear modulo controlador
Crear modulo modelo
Crear en java el modulo com.wordle.dao
implementar la conexion a la base de datos creada en el sprint 2 y 3



RNF

La logica de la matriz del juego debe tener restriccion para el uso de numeros y caracteres especiales.
