### ISSUE TITLE
H.U2 Instrucciones de juego

### ISSUE THREAD

**Issue by wipacheco1** [andresfgal/co.edu.poli.wordle#7]
Como usuario
Quiero que exista una ventana
Para que pueda mostrar las instrucciones del juego 

CRITERIOS ACEPTACIÓN

- [x] Botón con un icono en forma de signo de interrogación en la parte superior del entorno de juego.
- [x] Al dar clic en el botón (?) despliega una ventana con las instrucciones de juego
- [x] La ventana de instrucciones tendrá un icono *x* que permita regresar al entorno de juego

TAREA

- [x] Crear el entorno visual con la herramienta Scene Builder, primero abrir este software
- [x] Diseñar ventana del espacio de juego en scenebuilder con AnchorPane > Pane, en esta ventana se encontrará el botón de ayuda que genera una pantalla emergente con las instrucciones del juego. 
![espacioblanco](https://user-images.githubusercontent.com/112036650/187335581-9e587356-d4e7-45fd-8c7c-0c53fd3fe74f.JPG)

- [x]  Ubicar un botón de ayuda con un signo de interrogación en la parte izquierda superior de la ventana, asignar ID al botón de ayuda como un identificador.

![ayudaboton](https://user-images.githubusercontent.com/112036650/187335993-2961b1ec-df0a-4ae4-b91a-7a400cb65e10.JPG)

- [x] El botón de ayuda "?" deberá generar una ventana emergente, en esta ventana se encontrará un TextArea con las instrucciones de juego.

<img width="290" alt="Instu" src="https://user-images.githubusercontent.com/79174696/187344209-c76eed51-0cae-47fc-8e3b-351e0bc28686.png">

- [x] La ventana emergente debera contener el icono "X" en la parte superior derecha (como un botón) que permitirá regresar a la ventana de entorno de juego. 

<img width="140" alt="x1" src="https://user-images.githubusercontent.com/79174696/187344301-b4964f3e-b3b8-4e97-80f2-f6e52afb4455.png">
<img width="280" alt="tex2" src="https://user-images.githubusercontent.com/79174696/187344803-438e07a3-a133-477f-9428-886d705a6130.png">

RNF

- [x] El botón de ayuda debe ser color gris 
- [x] El botón de ayuda deberá tener un icono de signo de interrogación
- [x] El icono *x* de la ventana instrucciones debe ser de color rojo para dar visibilidad al usuario

**Comment by andresfgal** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/PracticaAplicada-62fe5153ed8de2001af076fe/issues/andresfgal/co.edu.poli.wordle/7?planning-poker) with ZenHub @Soflorez1
